language: node_js
node_js:
  - '8'
addons:
  chrome: stable
branches:
  - develop
  - /^release-.*$/
  - master
notifications:
  email:
    recipients:
      - j.bernal@upm.es
# Deploy https://betca-tpv-spring.herokuapp.com/api/v0/swagger-ui.html
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
