language: node_js
node_js:
  - '8'
before_install:
  - npm install -g @angular/cli
install: npm install
after_script:
  - chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
branches:
  only:
    - develop
    - master


